language: minimal
before_deploy:
  - git config --local user.name "Stephan Schwarz"
  - git config --local user.email "stearz@gmx.de"
  - export TRAVIS_TAG=$(cat VERSION)
  - git show-ref --tags | egrep -q "refs/tags/$TRAVIS_TAG$" && { echo 'version already exists' ; exit 1; } || git tag $TRAVIS_TAG
  - tar czvf /tmp/php-redirect-server.tar.gz ./* --exclude './VERSION' --exclude './.gitignore'
deploy:
  provider: releases
  api_key:
    secure: VVwxROoEaTOK0leAqtIGqqm2u6K12pLxqfqVGwVG3+CAUX1inNsiJJVfHlaFgirQcv4ns4aFVQf49iJhX5Od+W4pABXNBJkalznBq5MiuHYmNASazMHr2C/E/hEDNk0EyvwJOIZShHzBdV9Gi6cbRlPhyzPyFmqeT9OSK0erlrQ5c2r768U7DMjdpB0P2w8T78iR2tX+r8wl93mU292Y0pFVWlnQkNkFCCednyMmkI3TNq7a0IjARYv2Wif8/R3bB3TKg5XwBtffOnL/VNfK+TP9ogHsT3atN5VFpaSk6hnsMEydGTe3fJIVNNLNYGl/pd47JhFmDpzpBZrcLe4U8a1B6CAxiyY1OFGJ6EbQ2Yfhm+vBqyN4Z3Ss9v7wipoxT1FSCoNw8qt+MimNQYZTniubWqw7PL1q3Z0fWfOq98RVAe+3c1+Mnuf993vWAIr/Wi5wNiPUa50cMM6eC7bedPXeoMHQ7kdGn8iUcuuNQa2zIHU8bgyVXiaZ7NXas8UMYHViwITdNX749k7LMkORxNa1URWHifr1lIBfP2+rrWd1DPNf24mxUcUdIa8gIeGFuoamm5USBN6+vO+iLPCcMWJT6DL/7tggz9n9Zv230/WdLRyCGr/EiLQdNCCzjqD7NUIdlaZD01g+Dp90YKYpFytRU+Wt0x6n8cLx8DK3vtk=
  file: "/tmp/php-redirect-server.tar.gz"
  on:
    repo: stearz/php-redirect-server
  skip_cleanup: 'true'
